### ISSUE TITLE
Open source fiber coupled bilateral LED for in vivo applications 11_09_2015

### ISSUE THREAD

**Issue by andersjasp** [andersjasp/cyclops#1]
[Open source fiber coupled bilateral LED for in vivo applications 11_09_2015.pdf](https://github.com/andersjasp/cyclops/files/70035/Open.source.fiber.coupled.bilateral.LED.for.in.vivo.applications.11_09_2015.pdf)

**Comment by andersjasp** [comment]
Open source fiber coupled bilateral LED for in vivo applications 11_09_2015

**Comment by jonnew** [comment]
I'm closing this as it seems to be a reference to the pull request and not an issue.
